version: '3'

services:
  steam-reviews:
    build:
      context: .
      dockerfile: Dockerfile
    image: steam_reviews
    container_name: steam_reviews
    restart: on-failure
    ports:
      - '3001:3001'
    networks:
      - reviews-network
    depends_on:
      - reviews_db
    links:
      - reviews_db
    command: ./scripts/wait-for.sh reviews_db:5432 -- sh -c "npm run seed && exec node server/index.js"

  reviews_db:
    image: postgres:12
    container_name: reviews_db
    restart: on-failure
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=steam_reviews
    ports:
      - '5432:5432'
    networks:
      - reviews-network

networks:
  reviews-network:
    driver: bridge

volumes:
  pgdata:
